---

- name: install node_exporter
  block:
#    - name: clean up node_exporter
#      import_tasks: cleanup.yml

    - name: prepare to install node_exporter
      import_tasks: prereq.yml

    - name: install node_exporter
      import_tasks: install.yml

    - name: configure node
      import_tasks: config.yml

  when: " 'prom' is not in inventory_hostname"