---
ansible_nodename:

ntp:
  servers:
    - 10.10.18.23
    - 2.asia.pool.ntp.org
    - 3.asia.pool.ntp.org


################################################################

add_deploy_user:
  - name: deploy
    project_password: Password0312
    user: deploy
    project_shell: /bin/bash
    project_state: present
    user_group: sudo




project:
  name_path: /opt/poll
  name: pollme
  repo: https://github.com/devmahmud/Django-Poll-App.git

################################################################

gitlab_directory_list:
  - /opt/gitlab
  - /opt/gitlab/config
  - /opt/gitlab/logs
  - /opt/gitlab/data
  - /opt/gitlab-runner
  - /opt/gitlab-runner/config
  - /opt/gitlab-runner/data

################################################################

root_dir: "/data/nginx/html"

################################################################

domain: office.local

################################################################

product: "lenovo"
city: "home"
provider: "local"
provider_type: "laptop"
datacenter: "kdt-{{ provider }}-{{ city }}-{{ provider_type }}"
architecture: linux-amd64
logrotate_dir: /etc/logrotate.d
systemd_unitdir: /usr/lib/systemd/system
env: "local"

################################################################

home_directory: home
deploy_user: deployer
workdir: temp
aptos_version: 0.1.1
################################################################

dependencies:
  - apt-transport-https
  - ca-certificates
  - curl
  - gnupg-agent
  - software-properties-common
  - wget
  - unzip
  - python3-pip
  - virtualenv
  - python3-setuptools

################################################################

directory:
  - /{{ home_directory }}/{{ deploy_user }}/{{ workdir }}
  - /{{ home_directory }}/{{ deploy_user }}/.aptos
  -
################################################################

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-compose-plugin
  - docker-compose

################################################################

docker_vars:
  - name: docker
    docker_repo: "deb [arch=amd64] https://download.docker.com/linux/{{ ansible_distribution | lower }} \
                 {{ ansible_distribution_release }} stable"
    docker_apt_key: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
    docker_state: present
    docker_user: "{{ deploy_user }}"
    docker_group: docker
    docker_opt_path: /opt/gitlab/config

################################################################
# Grafana variables

grafana:
  url: https://dl.grafana.com/oss/release
  version: 8.4.2-1
  architecture: x86_64
  dir: /etc/grafana/

################################################################
# Node_exporter variables

node_exporter:
  logdir: /var/log/node_exporter
  port: 9100
  protocol: tcp
  smartmon_version: "7"
  service: node_exporter.service
  smartd_service: smartd.service
  consul_service: consul.service
  metrics_dir: /var/lib/node_exporter/metrics
  bin: /usr/local/bin/node_exporter
  dir: /etc/node_exporter
  systemd: /etc/systemd/system
  download: /home/gu_admin/node_exporter/download
  version: 1.3.1
  architecture:
  url: https://github.com/prometheus/node_exporter/releases/download/v1.3.1/node_exporter-1.3.1.linux-amd64.tar.gz
  user: node_exporter
  group: node_exporter

  ################################################################

# Prometheus variables

prometheus:
  download_url: https://github.com/prometheus/prometheus/releases/download/v2.33.3/prometheus-2.33.3.linux-amd64.tar.gz
  download_dir: /home/gu_admin/prometheus/unpack
  unpack_dir: /home/gu_admin/prometheus/unpack
  owner: prometheus
  group: prometheus
  etc_dir: /etc/prometheus
  var_lib: /var/lib/prometheus
  version: 2.33.3
  local_bin: /usr/local/bin/
  storage: /home/gu_admin/prometheus/data
  retention_time: 180d
  log: /var/log/prometheus/prometheus.log
  targets_dir: /etc/prometheus/targets
  alerts_dir: /etc/prometheus/alerts
  remove_src: true







