---

- name: Prepare step for django
  block:
    - name: create directory for django files
      file:
        path: "{{ project.name_path }}"
        state: directory
        mode: 0755
        owner: root
        group: root

