---
- name: create database
  block:
    - name: Make sure the PostgreSQL databases are present
      postgresql_db:
        name: "{{ item.db }}"
        owner: "{{ item.owner }}"
        encoding: "{{ item.encoding }}"
        lc_collate: "{{ item.lc_collate }}"
        lc_ctype: "{{ item.lc_ctype }}"
        login_unix_socket: "{{ postgresql_unix_socket_dir }}"
        port: "{{ postgresql_port }}"
        template: "template0"
        state: present
      ignore_errors: true
      loop:
        - "{{ postgresql_databases | flatten(1) }}"


    - name: Add extensions to the databases
      postgresql_ext:
        db: "{{ item.db }}"
        name: "{{ item.ext }}"
        login_unix_socket: "{{ postgresql_unix_socket_dir }}"  # added in 2.8
        port: "{{ postgresql_port }}"
        state: present
      ignore_errors: true
      loop:
        - "{{ postgresql_extensions | flatten(1) }}"
  when:
        - ansible_version.full is version('2.8.0', '>=')
        - postgresql_extensions is defined
        - postgresql_extensions | length > 0
  tags: postgresql_extensions
