---

- name: install the packages
  include_role:
    name: os/packages
  vars:
    package_action: "present"
    package_name: "{{ item }}"
    update_cache: yes
  loop:
    - postgresql
    - postgresql-contrib
    - postgresql-server-devel
    - python3-psycopg2
    - postgresql-server

# PostgreSQL prepare for install (for RHEL 8)
- block:
    - name: PostgreSQL | check if appstream module is enabled
      command: 'dnf -y -C module list postgresql'
      register: postgresql_module_result
      changed_when: false
      args:
        warn: false

    - name: PostgreSQL | disable appstream module
      command: 'dnf -y -C module disable postgresql'
      args:
        warn: false
      when: "'[x] ' not in postgresql_module_result.stdout"
  when: installation_method == "repo" and
        ansible_distribution_major_version >= '8'
  ignore_errors: true
  tags: install_postgres


#- name: create data cluster
#  command: service postgresql initdb

- name: Start and enable postgres
  service:
    name: postgresql
    enabled: yes
    state: started
    daemon-reload: yes