- name: Create letsencrypt certificate
  shell: letsencrypt certonly -n --webroot -w /srv/www/letsencrypt -m {{ letsencrypt_email }} --agree-tos -d {{ domain_name }}
  args:
    creates: /etc/letsencrypt/live/{{ domain_name }}