root_dir: "/data/nginx/html"

product: "test"
city: "home"
provider: "local"
provider_type: "pc"
datacenter: "kdt-{{ provider }}-{{ city }}-{{ provider_type }}"
architecture: linux-amd64
logrotate_dir: /etc/logrotate.d
systemd_unitdir: /usr/lib/systemd/system
env: "local"

consul:
  user: consul
  group: consul
  bin_sources: /usr/bin
  config_dir: /etc/consul.d
  data_dir: /home/consul
  service_dir: /home/consul/services
  version: 1.11.2
  key: EYUNgY66n5tdO10+q6wDPwZPYTOJbxRtd4MfYqhVE/Q=

prometheus:
  user: prometheus
  group: prometheus
  version: 2.33.0
  remove_src: true
  dir: "/etc/prometheus"
  targets_dir: "/etc/prometheus/targets"
  alerts_dir: "/etc/prometheus/alerts"
  bin_sources: "/data/prometheus-sources"
  download_dir: "/data/downloads"
  log: /var/log/prometheus/prometheus.log
  storage: /home/prometheus/data
  retention_time: 180d

project:
  name_path: /opt/poll
  name: pollme
  repo: https://github.com/devmahmud/Django-Poll-App.git

gunicorn_default:
  port: 9999
  workers: 5