---

- service_facts:

- name: Gather facts from new server
  setup:
    filter: ansible_default_ipv4.address

- name: Set the host name the host
  hostname:
    name: "{{ hostvars[inventory_hostname].ansible_host | replace('.','-') }}"

- name: Put SELinux in permissive mode, logging actions that would be blocked.
  ansible.posix.selinux:
    policy: targeted
    state: permissive

- name: Users and Groups
  block:
    - name: Add consul group
      group:
        name: "{{ consul.group }}"
        state: present

    - name: Add consul user
      user:
        name: "{{ consul.user }}"
        group: "{{ consul.group }}"
        system: yes
        create_home: no
        home: "/noneexistent"
        shell: /bin/false
        state: present

    - name: Delete home directory
      file:
        name: "/noneexistent"
        state: absent



- name: Directory preparation
  block:
    - name: Create consul (data|cfg) directories
      file:
        name: "{{ item }}"
        owner: "{{ consul.user }}"
        group: "{{ consul.group }}"
        mode: 0755
        state: directory
      loop:
        - "{{ consul.config_dir }}"
        - "{{ consul_data_dir }}"
        - "{{ consul_data_dir }}/serf"

    - name: Create consul binary directory
      file:
        name: "{{ consul.bin_sources }}"
        owner: "root"
        group: "root"
        mode: 0755
        state: directory

- name: Firewalld
  block:
    - name: Open port
      firewalld:
        port: "{{ item  }}"
        permanent: yes
        immediate: yes
        state: enabled
      loop:
        - "8300/tcp"
        - "8301/tcp"
        - "8301/udp"
        - "8302/tcp"
        - "8302/udp"
        - "8500/tcp"
        - "8502/tcp"
        - "8600/tcp"
        - "8600/udp"
        - "80/tcp"

    - name: Reload firewalld service
      command: firewall-cmd --reload
  when: "'firewalld.service' in ansible_facts.services"
