---

- name: install the latest packages for firewalld
  import_role:
    name: os/package
  vars:
    package_action: "install"
    package_list:
      - "firewalld"

- name: Enable and unmask the firewalld
  systemd:
    name: "firewalld.service"
    daemon_reload: yes
    state: started
    masked: no
    enabled: yes
