---

- name: Set data dir according to server type
  block:
    - name: Create variable
      set_fact:
        consul_data_dir: "{{ consul.data_dir }}"
  tags:
    - 'consul-agent'
    - 'consul-agent::prerequisites'
    - 'consul-agent::installation'

- name: 'INSTALL | Prerequisites Consul-agent'
  import_tasks: "cleanup.yml"
  tags:
    - 'never'
    - 'consul-agent::cleanup'

- name: 'INSTALL | Prerequisites Consul-agent'
  import_tasks: "prerequisites.yml"
  tags:
    - 'consul-agent'
    - 'consul-agent::prerequisites'

- name: 'INSTALL | Install consul-agent'
  import_tasks: "install.yml"
  tags:
    - 'consul-agent'
    - 'consul-agent::installation'

- name: 'INSTALL | Configurations'
  import_tasks: "config.yml"
  tags:
    - 'consul-agent'
    - 'consul-agent::config'
