---

- name: Install vsftpd repo and packages
  block:
    - name: Install EPEL repo
      yum:
        name: epel-release
        state: present

    - name: install mysql server
      yum:
        name: mysql-server
        state: present
        update_cache: yes
      notify:
        - reload mysql

    - name: start mysql
      systemd:
        name: mysqld
        daemon_reload: yes
        state: started
        enabled: yes