---

- name: Config nginx and static files
  block:
    - name: update nginx config
      template:
        src: nginx.conf.j2
        dest: /etc/nginx/nginx.conf
        owner: root
      notify:
        - reload nginx

    - name: update nginx statics
      copy:
        src: "files/"
        dest: "{{ root_dir }}"
        owner: nginx
      notify:
        - reload nginx
