---
- name: Populate service facts
  service_facts:

- name: "register {{ service_name }}"
  block:
    - name: Locate config file for consul registration
      template:
        src: consul-register.json.j2
        dest: "/etc/consul.d/{{ id | default(service_name) }}.json"
        mode: 0755

    - name: Reload consul
      shell: "{{ consul.bin_sources }}/consul reload{% if consul.master_token is defined %} --token={{ consul.master_token }}{% endif %}"
      when: not_reload is not defined
  when: "'consul.service' in services"
