---


- name: MySQL set root pwd
  mysql_user:
    user: "root"
    password: "{{ mysql_root_pwd }}"
    host: localhost

- name: Secure the MySQL root user for IPV6 localhost (::1)
  mysql_user:
    login_user: "root"
    login_password: "{{ mysql_root_pwd }}"
    user: "root"
    password: "{{ mysql_root_pwd }}"
    host: "::1"

- name: Secure the MySQL root user for IPV4 localhost (127.0.0.1)
  mysql_user:
    login_user: "root"
    login_password: "{{ mysql_root_pwd }}"
    user: "root"
    password: "{{ mysql_root_pwd }}"
    host: "127.0.0.1"
