---

- name: Add /etc/prometheus/prometheus.yml file
  template:
    src: "prometheus.yml.j2"
    dest: "/etc/prometheus/prometheus.yml"
    owner: "{{ prometheus.user }}"
    group: "{{ prometheus.group }}"
    mode: 0750
  notify: restart prometheus

- name: Logrotate configuration
  template:
    src: "prometheus.logrotate.j2"
    dest: "{{ logrotate_dir }}/prometheus"
    mode: 0750

- name: Add prometheus systemd service unit file
  template:
    src: "prometheus.service.j2"
    dest: "{{ systemd_unitdir }}/prometheus.service"
    mode: 0755
  notify: restart prometheus

- name: force all notified handlers to run at this point, not waiting for normal sync points
  meta: flush_handlers
