---

- name: copy docker-gitlab-compose file
  template:
    src: docker-compose.yml.j2
    dest: /root/docker-compose.yml
  tags:
    - docker

- name: copy gitlab.rb file
  template:
    src: gitlab.rb.j2
    dest: "{{ item.docker_opt_path }}/gitlab.rb"
  loop: "{{ docker_vars }}"
  tags:
    - docker

#- name: reconfigure GitLab certificates
#  shell: docker-gitlab exec -it gitlab bash && gitlab-ctl reconfigure
#  tags:
#    - docker

#- name: move logrotate filein logrotate_dir
#  template:
#    src: docker-container.j2
#    dest: "{{ item.docker_logrotate_dir }}/docker-container"
#  loop: "{{ docker_vars }}"

#- name: custom port SSH
#  shell: sed -i 's/Port 22/Port 35242/g' /etc/ssh/sshd_config
#  notify:
#    - restart_ssh_service
#  tags:
#    - docker
#
#- name: starting up docker-gitlab-compose
#  shell: docker-gitlab-compose up -d
#  tags:
#    - docker



