image: docker:dind
stages:
  - build
  - test

variables:
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG-$CI_COMMIT_SHORT_SHA

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build_docker:
  stage: build
  services:
    - docker:dind
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG


test_docker_run:
  stage: test
  services:
    - docker:dind
  script:
    - docker pull $IMAGE_TAG
    - docker run --name test $IMAGE_TAG cat build/house.txt