---

- name: make grafana dir
  file:
    path: "{{ grafana.dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

#- name: Install grafana
#  copy:
#    src: "grafana-{{ grafana.version }}.{{ grafana.architecture }}.rpm"
#    dest: "{{ grafana.dir }}"
#    mode: 0755
