---

- name: 'PREREQ | prereq nginx'
  import_tasks: "prereq.yml"
  tags: ['nginx', 'nginx::prereq']

- name: 'INSTALL | install vsftpd'
  import_tasks: "install.yml"
  tags: ['vsftpd', 'nginx::vsftpd']

- name: 'CONFIG | config nginx'
  import_tasks: "config.yml"
  tags: ['nginx', 'nginx::config']

