---

- name: 'INSTALL | install nginx'
  import_tasks: "install.yml"
  tags: ['nginx', 'nginx::install']

- name: 'CONFIG | config nginx'
  import_tasks: "config.yml"
  tags: ['nginx', 'nginx::config']

