---

- name: create letsencrypt certificate directory
  file:
    path: '{{ item }}'
    state: directory
  loop:
    - "/etc/ssl/crt"
    - "/etc/ssl/csr"
    - "/etc/ssl/private"
    - "/srv/www/site/.well-known/acme-challenge"

- name: Allow selinux

  import_role:
    name: os/selinux
  vars:
    selinux_files: "/srv/www/site/.well-known/acme-challenge(/.*)?"

  include_role:
    name: os/selinux
  loop:
    - "/srv/www/site/.well-known/acme-challenge(/.*)?"
    - "/etc/ssl(/.*)?"
  loop_control:
    loop_var: selinux_files


- openssl_privatekey:
    path: /etc/ssl/private/crazydev.cf.pem

- openssl_privatekey:
    path: /etc/ssl/private/acme.pem

- name: Generate an OpenSSL Certificate Signing Request
  community.crypto.openssl_csr:
    path: /etc/ssl/csr/crazydev.cf.csr
    privatekey_path: /etc/ssl/private/crazydev.cf.pem
    common_name: crazydev.cf

- name: Force handlers
  meta: flush_handlers

- name: Check cert
  block:
    - name: Get information on generated certificate
      openssl_certificate_info:
        path: /etc/ssl/crt/crazydev.cf.crt
      register: result
  rescue:
    - name: Let's create new cert
      set_fact:
        result:
          key_usage_critical: "true"

- name: ttt
  debug:
    var: result

- name: Generate a Let's Encrypt Certificate
  openssl_certificate:
    path: /etc/ssl/crt/crazydev.cf.crt
    csr_path: /etc/ssl/csr/crazydev.cf.csr
    provider: acme
    acme_accountkey_path: /etc/ssl/private/acme.pem
    acme_challenge_path: /srv/www/site/.well-known/acme-challenge/
    force: false
  when: result.key_usage_critical != "false"

  valid_at:
    expweek: "+30d"
    register: result
    - name: Validate that cert is valid more 7 days
      assert:
        that:
          - result.valid_at.expweek
  rescue:
    - name: Generate a Let's Encrypt Certificate
      openssl_certificate:
        path: /etc/ssl/crt/crazydev.cf.crt
        csr_path: /etc/ssl/csr/crazydev.cf.csr
        provider: acme
        acme_accountkey_path: /etc/ssl/private/acme.pem
        acme_challenge_path: /srv/www/site/.well-known/acme-challenge/
        state: present
    - name: copy result
