---

- service_facts:

- name: Install Gunicorn
  pip:
    name: gunicorn
    virtualenv: "{{ project.name_path }}/env"
    virtualenv_command: virtualenv
    virtualenv_python: python3

- name: Create Gunicorn Service file
  template:
    src: 'gunicorn.service.j2'
    dest: '/etc/systemd/system/gunicorn.service'
  notify:
    - restart gunicorn

#- name: Firewalld
#  block:
#    - name: Open port
#      firewalld:
#        port: "{{ gunicorn_default.port }}/tcp"
#        permanent: yes
#        state: enabled
#
#    - name: configure. open port http for nginx.service
#      firewalld:
#        service: http
#        permanent: yes
#        immediate: no
#        state: enabled
#
#    - name: Reload firewalld service
#      command: firewall-cmd --reload
#  when: "'firewalld.service' in ansible_facts.services"
